web-smsserver/config/routes.rb
WebSmsserver::Application.routes.draw do

  root to: redirect('/channels')

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                                    registrations: 'users/registrations',
                                    sessions: 'users/sessions',
                                    passwords: 'users/passwords',
                                    unlocks: 'users/unlocks'}

  get 'channels' => 'channel#index', as: :channels
  get "channels/:channel_id/messages", to: redirect('channels/%{channel_id}/messages/list/1'), as: :channels_messages_index
  get "channels/:channel_id/messages/list/(:page)" => 'message#index', as: :channels_messages_page
  get "channels/:channel_id/messages/:id/show" => 'message#show', as: :channels_messages_show
  get "channels/:channel_id/messages/new" => 'message#new', as: :channels_messages_new
  post "channels/:channel_id/messages/create" => 'message#create', as: :channels_messages_create

  namespace :api do
    namespace :v1  do
      namespace :send_sms  do
        post 'sendsms'
      end
      namespace :users, only: [] do
        get '', action: :search, as: "search"
        get ':user_id', action: :show, as: "show"
      end
    end
  end

  namespace :admin do
    get 'index' => 'main#index'

    namespace :users do
      get :list
      get :new
      post :create
      get ":user_id/edit", action: :edit, as: "edit"
      put ":user_id/update" , action: :update, as: "update"
      delete ":user_id/destroy" , action: :destroy, as: "destroy"
    end

    namespace :channels do
      get :list
      get :new
      post :create
      get ":channel_id/edit", action: :edit, as: "edit"
      put ":channel_id/update" , action: :update, as: "update"
      delete ":channel_id/destroy" , action: :destroy, as: "destroy"
      post ":channel_id/members/create", to: "members#create", as: "members_create"
      delete ":channel_id/members/:user_id/destroy", to: "members#destroy", as: "members_destroy"
      post ":channel_id/connections/create", to: "connections#create", as: "connections_create"
      put ":channel_id/connections/:connect_id/update", to: "connections#update", as: "connections_update"
      delete ":channel_id/connections/:connect_id/destroy", to: "connections#destroy", as: "connections_destroy"
    end
  end

end

web-smsserver/app/models/channel.rb
class Channel < ActiveRecord::Base
  after_create :create_channel_connection

  has_many :channel_connections
  has_many :messages

  has_many :memberships
  has_many :members, through: :memberships, class_name: User

  validates :name,  presence: true,
                    :format => {:with => /\A[a-z0-9\-\_]+\z/i},
                    length: {minimum: 3, maximum: 254},
                    :uniqueness => {
                        :case_sensitive => false
                    }
  validates :queue_name,  presence: true,
                          :format => {:with => /\A[a-z0-9\-\_]+\z/i},
                          length: {minimum: 3, maximum: 254},
                          :uniqueness => {
                              :case_sensitive => false
                          }
  validates :smpp_port, presence: true, numericality: :true
  validates :smpp_username, length: {minimum: 1, maximum: 16}, presence: true
  validates :smpp_password, length: {minimum: 1, maximum: 9}, presence: true
  validates :smpp_source_addr, length: {minimum: 1, maximum: 255}, presence: true
  validates :smpp_source_ton, presence: true, numericality: true
  validates :smpp_source_npi, presence: true, numericality: true
  validates :smpp_dest_ton, presence: true, numericality: true
  validates :smpp_dest_npi, presence: true, numericality: true
  validates :smpp_max_split_message, presence: true, numericality: true
  validates :smpp_max_message_per_second, presence: true, numericality: true
  validates :smpp_reconnect_timeout, presence: true, numericality: true
  validates :smpp_enquire_link_interval, presence: true, numericality: true

  def self.enable
    where(is_enable: true).load
  end

  def self.disable
    where(is_enable: false).load
  end

  def self.search(search, page)
    if search
      where('name ILIKE ? or queue_name ILIKE ?', "%#{search}%", "%#{search}%").page page
    else
      page page
    end
  end

  private

  def create_channel_connection
    ChannelConnection.create(channel: self, smpp_system_type: "")
  end

end

web-smsserver/app/controllers/admin/channels/connections_controller.rb
class Admin::Channels::ConnectionsController < Admin::BaseController
  before_filter :find_channel, only: [:create, :destroy, :update]
  before_filter :find_connect, only: [:update, :destroy]

  def create
    @connection = ChannelConnection.new(channel:@channel)
    if @connection.save
      create_successful
    else
      create_failed
    end
  end

  def destroy
    if @connection.destroy
      destroy_successful
    else
      destroy_failed
    end
  end

  def update
    if @connection.update(connection_params)
      update_successful
    else
      update_failed
    end
  end

  protected

  def find_channel
    @channel = Channel.find(params[:channel_id])
  end

  def find_connect
    @connection = ChannelConnection.find(params[:connect_id])
  end

  def connection_params
    params.require(:channel_connections).permit(:smpp_system_type)
  end

  def create_successful
    flash[:success] = "connection is created"
    redirect_to admin_channels_edit_path(@channel)
  end

  def create_failed
    flash[:error] = "connection is not create"
    redirect_to admin_channels_edit_path(@channel)
  end

  def update_successful
    flash[:success] = "connection is updated"
    redirect_to admin_channels_edit_path(@channel)
  end

  def update_failed
    flash[:error] = "update connection is problem"
    redirect_to admin_channels_edit_path(@channel)
  end

  def destroy_successful
    flash[:alert] = "connection is deleted"
    redirect_to admin_channels_edit_path(@channel)
  end

  def destroy_failed
    flash[:error] = "connection not deleted"
    redirect_to admin_channels_edit_path(@channel)
  end
end

web-smsserver/app/controllers/admin/channels/members_controller.rb
class Admin::Channels::MembersController < Admin::BaseController
  before_filter :find_channel, only: [:create, :destroy]
  before_filter :find_member, only: [:destroy]

  def create
    @membership = Membership.new(membership_params)

    if @membership.save
      create_successful
    else
      create_failed
    end
  end

  def destroy
    @membership = Membership.find_by(channel: @channel, member: @member)
    @membership.destroy if @membership
    destroy_successful
  end


  protected

  def find_channel
    @channel = Channel.find(params[:channel_id])
  end

  def find_member
    @member = User.find(params[:user_id])
  end

  def create_successful
    flash[:success] = "member #{@membership.member.email} is created"
    redirect_to admin_channels_edit_path(@channel)
  end

  def create_failed
    flash[:alert] = "member #{@membership.member.email} not created"
    redirect_to admin_channels_edit_path(@channel)
  end

  def destroy_successful
    flash[:error] = "member #{@member.email} is deleted"
    redirect_to admin_channels_edit_path(@channel)
  end

  def membership_params
    params.require(:memberships).permit(:member_id, :channel_permission_type_id, :channel_id)
  end
end

web-smsserver/app/controllers/admin/channels_controller.rb
class Admin::ChannelsController < Admin::BaseController
  before_filter :find_channel, only: [:edit, :update, :destroy]
  before_filter :find_members, only: [:edit, :update]

  def list
    @channels = Channel.search(params[:search], params[:page])
  end

  def new
    @channel = Channel.new
  end

  def create
    @channel = Channel.new(channel_params)

    if @channel.save
      create_successful
    else
      create_failed
    end
  end

  def edit

  end

  def update
    respond_to do |format|
      if @channel.update(channel_params)
        sms_api = SmsServerWebApi.new
        if @channel.is_enable
          sms_api.start(@channel)
        else
          sms_api.stop(@channel)
        end
        format.html { redirect_to admin_channels_edit_path(@channel), flash: {success: 'success update channel'} }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    if @channel.delete
      redirect_to admin_channels_list_path, flash: {alert: "channel: " + @channel.email + " is deleted " }
    else
      redirect_to admin_channels_edit_path(@channel), flash: {error: 'channel not deleted'}
    end
  end

  protected

  def find_members
    @memberships_channel = Membership.where(channel_id: @channel)
  end

  def find_channel
    @channel = Channel.find(params[:channel_id])
  end

  def channel_params
    params.require(:channel).permit!
  end

  def create_successful
    flash[:success] = "success create channel"
    redirect_to admin_channels_edit_path(@channel)
  end

  def create_failed
    render action: :new
  end

end

web-smsserver/app/controllers/channel_controller.rb
class ChannelController < ApplicationController
  before_filter :authenticate_user


  def index
    if is_admin?
      @channels = Channel.search(params[:search], params[:page]).order(is_enable: :desc)
    else
      @channels = current_user.channels.search(params[:search], params[:page]).order(is_enable: :desc)
    end
  end
end

web-smsserver/app/views/admin/channels/_form.haml
-# fix chrome autcomlpleate=off
= text_field_tag :prevent_autofill, "", style: "display:none;"
= password_field_tag :password_fake, "",  style: "display:none;"

.form-group
  = f.label :name
  = f.text_field :name, class: "form-control", placeholder: "name", autofocus: true, required: true, autocomplete: "off"

.form-group
  = f.label :queue_name
  = f.text_field :queue_name, class: "form-control", autocomplete: "off", required: true

.form-group
  = f.check_box :is_enable
  = f.label :is_enable

.form-group
  = f.check_box :is_fake
  = f.label :is_fake

.form-group
  = f.check_box :is_payload
  = f.label :is_payload

.form-group
  = f.label :smpp_host
  = f.text_field :smpp_host, class: "form-control", autocomplete: "off"

.form-group
  = f.label :smpp_port
  = f.text_field :smpp_port, class: "form-control", autocomplete: "off"

.form-group
  = f.label :smpp_username
  = f.text_field :smpp_username, class: "form-control", autocomplete: "off"

.form-group
  = f.label :smpp_password
  = f.text_field :smpp_password, class: "form-control", autocomplete: "off"

.form-group
  = f.label :smpp_source_addr
  = f.text_field :smpp_source_addr, class: "form-control", autocomplete: "off"

.form-group
  = f.label :smpp_source_ton
  = f.text_field :smpp_source_ton, class: "form-control", autocomplete: "off"

.form-group
  = f.label :smpp_source_npi
  = f.text_field :smpp_source_npi, class: "form-control", autocomplete: "off"

.form-group
  = f.label :smpp_dest_ton
  = f.text_field :smpp_dest_ton, class: "form-control", autocomplete: "off"

.form-group
  = f.label :smpp_dest_npi
  = f.text_field :smpp_dest_npi, class: "form-control", autocomplete: "off"

.form-group
  = f.label :smpp_max_split_message
  = f.text_field :smpp_max_split_message, class: "form-control", autocomplete: "off"

.form-group
  = f.label :smpp_max_message_per_second
  = f.text_field :smpp_max_message_per_second, class: "form-control", autocomplete: "off"

.form-group
  = f.label :smpp_reconnect_timeout
  = f.text_field :smpp_reconnect_timeout, class: "form-control", autocomplete: "off"

.form-group
  = f.label :smpp_enquire_link_interval
  = f.text_field :smpp_enquire_link_interval, class: "form-control", autocomplete: "off"

web-smsserver/app/views/admin/channels/edit.haml
- if @channel.errors.full_messages.any?
  .alert.alert-warning.alert-dismissable
    %ul
      - @channel.errors.full_messages.each do |msg|
        %li
          = msg

.col-lg-5
  = form_for :channel, url: admin_channels_update_path(@channel), method: :put  do |f|
    = render :partial => "form", :locals => { :f => f }
    = f.submit 'Update', :class => "btn btn-primary"

.col-lg-7
  = render :partial => 'admin/channels/connections/list'
  = render :partial => 'admin/channels/members/list'


:javascript
  $(document).ready( function() {
    $("[type='checkbox']").bootstrapSwitch();
  });

web-smsserver/app/views/admin/channels/list.haml
= form_tag admin_channels_list_path, method: :get, class: "form-inline" do
  .form-group
    = text_field_tag :search, params[:search], class: "form-control", placeholder: "name or queue"
  = button_tag name: nil, class:"btn btn-default btn-primary" do
    %span.glyphicon.glyphicon-search
    Search
  = link_to admin_channels_list_path, class:"btn btn-default" do
    %span.glyphicon.glyphicon-refresh
    Clear

%table.table.table-hover
  %thead
    %th
      Name
    %th
      Queue
    %th
      Connects
    %th
      Payload
    %th
      Fake
    %th
      Enable

  %tbody.channel
    - @channels.each do |channel|
      %tr
        %td
          = link_to channel.name, admin_channels_edit_path(channel.id)
        %td
          = channel.queue_name
        %td
          = channel.channel_connections.length
        %td
          = yes_no_label_tag(channel.is_payload)
        %td
          = yes_no_label_tag(channel.is_fake)
        %td
          = yes_no_label_tag(channel.is_enable, 'ENABLE', 'DISABLE')

= paginate @channels

web-smsserver/app/views/admin/channels/new.haml
.col-lg-5
  - if @channel.errors.full_messages.any?
    .alert.alert-warning.alert-dismissable
      %ul
        - @channel.errors.full_messages.each do |msg|
          %li
            = msg

  = form_for :channel, url: admin_channels_create_path, method: :post  do |f|
    = render :partial => "form", :locals => { :f => f }
    = f.submit 'Create', :class => "btn btn-primary"

-#.col-lg-5
-#  test


:javascript
  $(document).ready( function() {
    $("[type='checkbox']").bootstrapSwitch();
  });