web-smsserver/config/routes.rb
WebSmsserver::Application.routes.draw do

  root to: redirect('/channels')

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                                    registrations: 'users/registrations',
                                    sessions: 'users/sessions',
                                    passwords: 'users/passwords',
                                    unlocks: 'users/unlocks'}

  get 'channels' => 'channel#index', as: :channels
  get "channels/:channel_id/messages", to: redirect('channels/%{channel_id}/messages/list/1'), as: :channels_messages_index
  get "channels/:channel_id/messages/list/(:page)" => 'message#index', as: :channels_messages_page
  get "channels/:channel_id/messages/:id/show" => 'message#show', as: :channels_messages_show
  get "channels/:channel_id/messages/new" => 'message#new', as: :channels_messages_new
  post "channels/:channel_id/messages/create" => 'message#create', as: :channels_messages_create

  namespace :api do
    namespace :v1  do
      namespace :send_sms  do
        post 'sendsms'
      end
      namespace :users, only: [] do
        get '', action: :search, as: "search"
        get ':user_id', action: :show, as: "show"
      end
    end
  end

  namespace :admin do
    get 'index' => 'main#index'

    namespace :users do
      get :list
      get :new
      post :create
      get ":user_id/edit", action: :edit, as: "edit"
      put ":user_id/update" , action: :update, as: "update"
      delete ":user_id/destroy" , action: :destroy, as: "destroy"
    end

    namespace :channels do
      get :list
      get :new
      post :create
      get ":channel_id/edit", action: :edit, as: "edit"
      put ":channel_id/update" , action: :update, as: "update"
      delete ":channel_id/destroy" , action: :destroy, as: "destroy"
      post ":channel_id/members/create", to: "members#create", as: "members_create"
      delete ":channel_id/members/:user_id/destroy", to: "members#destroy", as: "members_destroy"
      post ":channel_id/connections/create", to: "connections#create", as: "connections_create"
      put ":channel_id/connections/:connect_id/update", to: "connections#update", as: "connections_update"
      delete ":channel_id/connections/:connect_id/destroy", to: "connections#destroy", as: "connections_destroy"
    end
  end

end

web-smsserver/app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :channel
  belongs_to :message_status

  def get_utf_message_data
    if self.esm_class == 64 and not self.is_payload
        [ self.message_data[0..5].unpack('H*')[0], Iconv.conv("UTF-8", "UTF-16BE",self.message_data[6..139])]
    else
        Iconv.conv("UTF-8", "UTF-16BE",self.message_data)
    end
  end

end

web-smsserver/app/controllers/message_controller.rb
class MessageController < ApplicationController
  before_filter :authenticate_user
  before_filter :find_message, only:[:show]
  before_filter :find_channel

  def index
    authorize! :read, @channel
    @messages = Message.where(channel_id: params[:channel_id] ).order(id: :desc).page(params[:page]).per(20)
  end

  def show
    authorize! :read, @channel

  end

  def new
    authorize! :read, @channel
    @inbound_message = InboundMessage.new
  end

  def create
    authorize! :read, @channel
    @inbound_message = InboundMessage.new(inbound_message_params)
    @inbound_message.channel = @channel
    if @inbound_message.valid?
      rmq = RabbitSms.new
      rmq.create_sms(@inbound_message)
      flash[:success] = "#{t('messages.notify.send.success')}"
      redirect_to channels_messages_new_path(@channel)
    else
      render 'new'
    end
  end

  protected

  def find_message
    @message = Message.find(params[:id])
  end

  def find_channel
    @channel = Channel.find(params[:channel_id])
  end

  def inbound_message_params
    params.require(:inbound_message).permit(:from, :to, :message_text)
  end
end

web-smsserver/app/views/message/_breadcrumb.haml
.row
  .col-lg-12
    %ol.breadcrumb
      %li
        = link_to channels_messages_index_path(@channel) do
          Channel (#{@channel.name})
      - if local_assigns[:is_new]
        %li
          Message
        %li.active
          New
      - elsif local_assigns[:is_show]
        %li
          Message
        %li.active
          Show (#{@message.id})
      - else
        %li.active
          Message list

.row
  .col-lg-12
    .channel-status
      %ul
        %li
          is_payload:
          - if @channel.is_payload
            %span.label.label-success
              YES
          - else
            %span.label.label-default
              NO
        %li
          is_fake:
          - if @channel.is_fake
            %span.label.label-success
              YES
          - else
            %span.label.label-default
              NO
        %li
          is_enable:
          - if @channel.is_enable
            %span.label.label-success
              YES
          - else
            %span.label.label-default
              NO

web-smsserver/app/views/message/index.haml
= paginate @messages

%table.table.table-hover
  %thead
    %th
      id
    %th
      status
    %th
      message_id
    %th
      addr_from
    %th
      addr_to
    %th
      message_data
    %th
      send_retry
    %th
      error_code

  %tbody.channel_message
    - @messages.each do |message|
      %tr
        %td
          = link_to message.id, channels_messages_show_path(message.channel, message)
        %td
          = message_status_label_tag(message.message_status.name)
        %td
          = link_to message.message_id, "#"
        %td
          - if message.addr_from
            = message.addr_from
          - else
            = message.channel.smpp_source_addr
        %td
          = message.addr_to
        %td.message-data
          .header
            .first-item
              seq_num:
              = message.sequence_number
            .item
              esm_class:
              = message.esm_class
            .item
              is_playload:
              = yes_no_label_tag(message.is_payload)
          .data
            - if message.is_payload or message.esm_class == 0
              = message.get_utf_message_data
            - else
              %span.label.label-info
                = message.get_utf_message_data[0]
              &nbsp;
              = message.get_utf_message_data[1]
        %td
          = message.send_retry
        %td
          = message.error_code


= paginate @messages

web-smsserver/app/views/message/new.haml
- if @inbound_message.errors.full_messages.any?
  .alert.alert-warning.alert-dismissable
    %button.close{type: 'button', 'data-dismiss' => "alert", 'aria-hidden' => 'true'}
      &times;
    %ul
      - @inbound_message.errors.full_messages.each do |msg|
        %li
          = msg
= form_for :inbound_message, url:channels_messages_create_path(@channel), method: "post" do |f|
  .form-group
    = label_tag :to, "To :"
    = f.text_field :to, class: "form-control"
  .form-group
    = label_tag :from, "From :"
    = f.text_field :from, class: "form-control"
  .form-group
    = label_tag :message_text
    = f.text_area :message_text, class: "form-control"

  = submit_tag "Send", class:"btn btn-primary"

web-smsserver/app/views/message/show.haml
id: #{@message.id}
%br