web-smsserver/config/routes.rb
WebSmsserver::Application.routes.draw do

  root to: redirect('/channels')

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                                    registrations: 'users/registrations',
                                    sessions: 'users/sessions',
                                    passwords: 'users/passwords',
                                    unlocks: 'users/unlocks'}

  get 'channels' => 'channel#index', as: :channels
  get "channels/:channel_id/messages", to: redirect('channels/%{channel_id}/messages/list/1'), as: :channels_messages_index
  get "channels/:channel_id/messages/list/(:page)" => 'message#index', as: :channels_messages_page
  get "channels/:channel_id/messages/:id/show" => 'message#show', as: :channels_messages_show
  get "channels/:channel_id/messages/new" => 'message#new', as: :channels_messages_new
  post "channels/:channel_id/messages/create" => 'message#create', as: :channels_messages_create

  namespace :api do
    namespace :v1  do
      namespace :send_sms  do
        post 'sendsms'
      end
      namespace :users, only: [] do
        get '', action: :search, as: "search"
        get ':user_id', action: :show, as: "show"
      end
    end
  end

  namespace :admin do
    get 'index' => 'main#index'

    namespace :users do
      get :list
      get :new
      post :create
      get ":user_id/edit", action: :edit, as: "edit"
      put ":user_id/update" , action: :update, as: "update"
      delete ":user_id/destroy" , action: :destroy, as: "destroy"
    end

    namespace :channels do
      get :list
      get :new
      post :create
      get ":channel_id/edit", action: :edit, as: "edit"
      put ":channel_id/update" , action: :update, as: "update"
      delete ":channel_id/destroy" , action: :destroy, as: "destroy"
      post ":channel_id/members/create", to: "members#create", as: "members_create"
      delete ":channel_id/members/:user_id/destroy", to: "members#destroy", as: "members_destroy"
      post ":channel_id/connections/create", to: "connections#create", as: "connections_create"
      put ":channel_id/connections/:connect_id/update", to: "connections#update", as: "connections_update"
      delete ":channel_id/connections/:connect_id/destroy", to: "connections#destroy", as: "connections_destroy"
    end
  end

end

web-smsserver/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:ldap]

  has_many :memberships, foreign_key: :member_id
  has_many :channels, :through =>  :memberships, :class_name => Channel, :source => :channel

  attr_accessor :login

  before_create :generate_token

  validates :username,  presence: true,
            :format => {:with => /\A[a-z0-9\-\_]+\z/i},
            length: {minimum: 3, maximum: 254},
            :uniqueness => {
                :case_sensitive => false
            }

  scope :user_search, -> { order(is_admin: :desc) }

  class << self
    def get_user_by_token(token)
      return nil if token.nil?
      begin
        User.find_by_token(token)
      rescue ActiveRecord::RecordNotFound
        return nil
      end
    end

    def find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions).first
      end
    end

    def search(search, page)
      if search
        user_search.where('username ILIKE ? or email ILIKE ?', "%#{search}%", "%#{search}%").page page
      else
        user_search.page page
      end
    end
  end

  def generate_token
    self.token = Digest::MD5.hexdigest((0...32).map { ('a'..'z').to_a[rand(26)] }.join + self.email)
  end

  def get_permission_by_channel(channel, permission_type_name=nil)
    if permission_type_name
      return memberships.where(channel:channel, channel_permission_types: {name: permission_type_name}).first
    end
    memberships.where(channel: channel).first
  end

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

end

web-smsserver/app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_filter :find_user, only: [:edit, :update, :destroy]

  def list
    @users = User.search(params[:search], params[:page])
  end

  def show

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params(false))

    if @user.save
      create_successful
    else
      create_failed
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params(true))
        format.html { redirect_to admin_users_edit_path(@user), flash: {success: 'success update user'} }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    if @user.destroy
      redirect_to admin_users_list_path, flash: {alert: "user: " + @user.email + " is deleted " }
    else
      redirect_to admin_users_edit_path(@user), flash: {error: 'user not deleted'}
    end
  end

  protected

  def user_params(is_update)
    tmp_params = params.require(:user).permit(:email, :password, :password_confirmation, :is_admin, :username)
    if is_update and tmp_params[:password].blank?
      tmp_params.delete(:password)
      tmp_params.delete(:password_confirmation) if tmp_params[:password_confirmation].blank?
    end
    tmp_params
  end

  def create_successful
    flash[:success] = "success create user"
    redirect_to admin_users_edit_path(@user)
  end

  def create_failed
    render :action => "new"
  end

  def find_user
    @user = User.find(params[:user_id])
  end
end

web-smsserver/app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::BaseController
  before_filter :authenticate_user

  def search
    username = params[:q]
    users = User.arel_table
    render json: User.where(users[:username].matches("%#{username}%")).limit(10), :only=> [:email, :id, :username]
  end

  def show
    render json: User.find(params[:user_id]), :only=> [:email, :id, :username]
  end
end

web-smsserver/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def ldap
    username = request.env["omniauth.auth"][:extra][:raw_info][Settings.ldap.uid][0]
    @user = User.find_by_username(username)
    if @user
      sign_in_and_redirect(@user)
    else
      flash[:alert] = "Access denied for your LDAP account."
      redirect_to new_user_session_path
    end
  end
end

web-smsserver/app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::SessionsController
  layout "devise"

  def update
    super
  end

  protected

  def after_resetting_password_path_for(resource)
    root_path
  end

  def resource_params
    params.fetch(resource_name, {})
  end
end

web-smsserver/app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  layout "devise"


  def new
    super
  end

  def create
    super
  end

  def destroy
    super
  end
end

web-smsserver/app/views/admin/users/_form.haml
-# fix chrome autcomlpleate=off
= text_field_tag :prevent_autofill, "", style: "display:none;"
= password_field_tag :password_fake, "",  style: "display:none;"

.form-group
  = f.label "Email"
  = f.text_field :email, class: "form-control", placeholder: "email", autofocus: true, required: true, autocomplete: "off"

.form-group
  = f.label "User Name"
  = f.text_field :username, class: "form-control", placeholder: "username", required: true, autocomplete: "off"

.form-group
  = f.label :password
  = f.password_field :password, class: "form-control", autocomplete: "off"

.form-group
  = f.label :password_confirmation
  = f.password_field :password_confirmation, class: "form-control", autocomplete: "off"

.form-group
  = f.check_box :is_admin
  = f.label :is_admin

web-smsserver/app/views/admin/users/edit.haml
- if @user.errors.full_messages.any?
  .alert.alert-warning.alert-dismissable
    %ul
      - @user.errors.full_messages.each do |msg|
        %li
          = msg
.col-lg-5
  = form_for :user, url: admin_users_update_path(@user), method: :put  do |f|
    = render :partial => "form", :locals => { :f => f }
    = f.submit 'Update', :class => "btn btn-primary"
.col-lg-5
  %h3
    Channels

  %table.table
    %thead
      %th
        channel
      %th
        permission
    %tbody
      - @user.memberships.each do |membership|
        %tr
          %td
            = membership.channel.name
          %td
            = membership.channel_permission_type.name

:javascript
  $(document).ready( function() {
    $("[type='checkbox']").bootstrapSwitch();
  });

web-smsserver/app/views/admin/users/list.haml
= form_tag admin_users_list_path, method: :get, class: "form-inline" do
  .form-group
    = text_field_tag :search, params[:search], class: "form-control", placeholder: "email or username"
  = button_tag name: nil, class:"btn btn-default btn-primary" do
    %span.glyphicon.glyphicon-search
    Search
  = link_to admin_users_list_path, class:"btn btn-default" do
    %span.glyphicon.glyphicon-refresh
    Clear

-#= User.attribute_names
%table.table
  %thead
    %th

    %th
      username
    %th
      email
    %th
      admin
    %th
      token

  %tbody
    - @users.each do |user|
      %tr
        %td
          = user_avatar(user)
        %td
          = link_to user.username, admin_users_edit_path(user)
        %td
          = link_to user.email, admin_users_edit_path(user)
        %td
          - if user.is_admin?
            %span.glyphicon.glyphicon-ok
        %td
          = user.token

= paginate @users


-#= user_avatar(user)
-#= link_to user.email, admin_users_edit_path(user)
-#= user.token
-#= user.is_admin?
-#= user.updated_at
-#= link_to 'Delete', admin_users_destroy_path(user), method: :delete, data: { confirm: "are you delete user: " + user.email }
-#%br

web-smsserver/app/views/admin/users/new.haml
- if @user.errors.full_messages.any?
  .alert.alert-warning.alert-dismissable
    %ul
      - @user.errors.full_messages.each do |msg|
        %li
          = msg

= form_for :user, url: admin_users_create_path do |f|
  = render :partial => "form", :locals => { :f => f }
  = f.submit 'Create', :class => "btn btn-primary"

:javascript
  $(document).ready( function() {
    $("[type='checkbox']").bootstrapSwitch();
  });