web-smsserver/config/routes.rb
WebSmsserver::Application.routes.draw do

  root to: redirect('/channels')

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                                    registrations: 'users/registrations',
                                    sessions: 'users/sessions',
                                    passwords: 'users/passwords',
                                    unlocks: 'users/unlocks'}

  get 'channels' => 'channel#index', as: :channels
  get "channels/:channel_id/messages", to: redirect('channels/%{channel_id}/messages/list/1'), as: :channels_messages_index
  get "channels/:channel_id/messages/list/(:page)" => 'message#index', as: :channels_messages_page
  get "channels/:channel_id/messages/:id/show" => 'message#show', as: :channels_messages_show
  get "channels/:channel_id/messages/new" => 'message#new', as: :channels_messages_new
  post "channels/:channel_id/messages/create" => 'message#create', as: :channels_messages_create

  namespace :api do
    namespace :v1  do
      namespace :send_sms  do
        post 'sendsms'
      end
      namespace :users, only: [] do
        get '', action: :search, as: "search"
        get ':user_id', action: :show, as: "show"
      end
    end
  end

  namespace :admin do
    get 'index' => 'main#index'

    namespace :users do
      get :list
      get :new
      post :create
      get ":user_id/edit", action: :edit, as: "edit"
      put ":user_id/update" , action: :update, as: "update"
      delete ":user_id/destroy" , action: :destroy, as: "destroy"
    end

    namespace :channels do
      get :list
      get :new
      post :create
      get ":channel_id/edit", action: :edit, as: "edit"
      put ":channel_id/update" , action: :update, as: "update"
      delete ":channel_id/destroy" , action: :destroy, as: "destroy"
      post ":channel_id/members/create", to: "members#create", as: "members_create"
      delete ":channel_id/members/:user_id/destroy", to: "members#destroy", as: "members_destroy"
      post ":channel_id/connections/create", to: "connections#create", as: "connections_create"
      put ":channel_id/connections/:connect_id/update", to: "connections#update", as: "connections_update"
      delete ":channel_id/connections/:connect_id/destroy", to: "connections#destroy", as: "connections_destroy"
    end
  end

end

web-smsserver/app/views/layouts/application.haml
!!! 5
%html
  %head
    = stylesheet_link_tag "application", media: :all
    = javascript_include_tag "application"
    = favicon_link_tag
    = csrf_meta_tags
  %body
    .container-fluid
      .row
        .col-lg-2.left-sidebar
          %ul.nav.nav-left-sidebar
            %li.login-info
              = link_to '#' do
                = user_avatar(current_user, { size: 32})
                = current_user.username
            %li{class: is_active?('(channel|message)')}
              = link_to channels_path do
                %span.glyphicon.glyphicon-tasks
                Channels
              - if is_active?('(channel|message)')
                %ul.nav.sub-action
                  %li{ class: is_active?('channel', 'index')}
                    = link_to channels_path do
                      %span.glyphicon.glyphicon-list
                      List
                  - if is_active?('message')
                    %li.channel-name
                      = link_to channels_messages_page_path(@channel) do
                        = @channel.name
                        = yes_no_label_tag(@channel.is_enable, 'ENABLE', 'DISABLE')
                    %li{class: is_active?('message', 'index')}
                      = link_to channels_messages_page_path(@channel), class: 'channel-action' do
                        = fa_icon 'comments-o'
                        List
                    %li{ class: is_active?('message', '(new|create)')}
                      = link_to channels_messages_new_path(@channel), class: 'channel-action' do
                        %span.glyphicon.glyphicon-plus
                        Create
                    - if is_active?('message', 'show')
                      %li.active
                        = link_to channels_messages_show_path(@channel, @message), class: 'channel-action' do
                          = fa_icon 'comment-o'
                          Show

            %li.group-menu-name
              = link_to '#' do
                Settings
            %li{ class: is_active?('admin/users')}
              = link_to admin_users_list_path do
                %span.glyphicon.glyphicon-user
                Users
              - if is_active?('admin/users')
                %ul.nav.sub-action
                  %li{ class: is_active?('admin/users', 'list')}
                    = link_to admin_users_list_path do
                      %span.glyphicon.glyphicon-list
                      List
                  %li{ class: is_active?('admin/users', '(new|create)')}
                    = link_to admin_users_new_path do
                      %span.glyphicon.glyphicon-plus
                      Create
                  - if is_active?('admin/users', '(edit|update)')
                    %li.active
                      = link_to admin_users_edit_path do
                        %span.glyphicon.glyphicon-edit
                        Edit
            %li{ class: is_active?('admin/channels')}
              = link_to admin_channels_list_path do
                %span.glyphicon.glyphicon-tasks
                Channels
              - if is_active?('admin/channels')
                %ul.nav.sub-action
                  %li{ class: is_active?('admin/channels', 'list')}
                    = link_to admin_channels_list_path do
                      %span.glyphicon.glyphicon-list
                      List
                  %li{ class: is_active?('admin/channels', '(new|create)')}
                    = link_to admin_channels_new_path do
                      %span.glyphicon.glyphicon-plus
                      Create
                  - if is_active?('admin/channels', '(edit|update)')
                    %li.active
                      = link_to admin_channels_edit_path do
                        %span.glyphicon.glyphicon-edit
                        Edit

            %li.logout
              = link_to destroy_user_session_path, method: :delete do
                Log out

        .col-lg-10.col-lg-offset-2.main
          - flash.each do |name, msg|
            %div{class: flash_class(name) }
              %button.close{type: "button", "data-dismiss" => "alert", "aria-hidden" => "true"}
                &times;
              = msg
          = content_for?(:content) ? yield(:content) : yield



    -#.footer
    -#  .container
    -#    test

web-smsserver/app/views/layouts/devise.haml
!!! 5
%html
  %head
    = stylesheet_link_tag "application", media: :all
    = javascript_include_tag "application"
    = favicon_link_tag
    = csrf_meta_tags
  %body.signin-container
    .container
      .signin-message
        - flash.each do |name, msg|
          %div{class: flash_class(name) }
            %button.close{type: "button", "data-dismiss" => "alert", "aria-hidden" => "true"}
              &times;
            = msg
      = content_for?(:content) ? yield(:content) : yield